version: "3"
services:
  tunellm:
    container_name: tunellm
    build:
      context: .
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: robinvandernoord/tunellm:latest
    ports:
      - "${PORT:-11434}:${PORT:-11434}"
    env_file:
      - .env
