version: "3"
services:
  tunnellm:
    container_name: tunnellm
    build:
      context: app
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: robinvandernoord/tunnellm:latest
    ports:
      - "${PORT:-11434}:${PORT:-11434}"
    env_file:
      - .env
